-- MySQL Script generated by MySQL Workbench
-- 06/07/16 05:31:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ticket3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticket3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket3` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema tickets
-- -----------------------------------------------------
USE `ticket3` ;

-- -----------------------------------------------------
-- Table `ticket3`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(60) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `precio` FLOAT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `ticket3`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombreEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombreSucursal` VARCHAR(90) NOT NULL,
  `direccion` VARCHAR(90) NOT NULL,
  `telefono` VARCHAR(10) NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idSucursal`, `idEstado`),
  INDEX `fk_Sucursal_Estado1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_Sucursal_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `ticket3`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Caja` (
  `idCaja` INT NOT NULL AUTO_INCREMENT,
  `noCaja` INT NOT NULL,
  `idSucursal` INT NOT NULL,
  PRIMARY KEY (`idCaja`, `idSucursal`),
  INDEX `fk_Caja_Sucursal1_idx` (`idSucursal` ASC),
  CONSTRAINT `fk_Caja_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `ticket3`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `idSucursal` INT NOT NULL,
  `idCaja` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `idSucursal_idx` (`idSucursal` ASC),
  CONSTRAINT `idSucursal`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `ticket3`.`Sucursal` (`idSucursal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Detalle` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `idTicket` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalle`, `idTicket`, `idProducto`),
  INDEX `idTicket_idx` (`idTicket` ASC),
  INDEX `fk_Detalle_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `idTicket`
    FOREIGN KEY (`idTicket`)
    REFERENCES `ticket3`.`Ticket` (`idTicket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Detalle_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `ticket3`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket3`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket3`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `idCaja` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Caja1_idx` (`idCaja` ASC),
  CONSTRAINT `idCaja`
    FOREIGN KEY (`idCaja`)
    REFERENCES `ticket3`.`Caja` (`idCaja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
