-- MySQL Script generated by MySQL Workbench
-- 12/05/16 14:58:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sucursal` INT NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `contrasena_UNIQUE` (`contrasena` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`cuenta` (
  `num_cuenta` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `NIP` INT NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  PRIMARY KEY (`num_cuenta`, `usuario_id`),
  INDEX `fk_cuenta_usuario_idx` (`usuario_id` ASC),
  UNIQUE INDEX `NIP_UNIQUE` (`NIP` ASC),
  CONSTRAINT `fk_cuenta_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `banco`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`ahorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`ahorro` (
  `id_horro` INT NOT NULL,
  `cuenta_num_cuenta` INT NOT NULL,
  `cuenta_usuario_id` INT NOT NULL,
  `saldo` INT NOT NULL,
  PRIMARY KEY (`id_horro`, `cuenta_num_cuenta`, `cuenta_usuario_id`),
  INDEX `fk_ahorro_cuenta1_idx` (`cuenta_num_cuenta` ASC, `cuenta_usuario_id` ASC),
  CONSTRAINT `fk_ahorro_cuenta1`
    FOREIGN KEY (`cuenta_num_cuenta` , `cuenta_usuario_id`)
    REFERENCES `banco`.`cuenta` (`num_cuenta` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`credito` (
  `id_credito` INT NOT NULL,
  `cuenta_num_cuenta` INT NOT NULL,
  `cuenta_usuario_id` INT NOT NULL,
  `saldo_cred` INT NOT NULL,
  `anualidad` INT NOT NULL,
  `interes` INT NOT NULL,
  `fecha_corte` INT NOT NULL,
  PRIMARY KEY (`id_credito`, `cuenta_num_cuenta`, `cuenta_usuario_id`),
  INDEX `fk_credito_cuenta1_idx` (`cuenta_num_cuenta` ASC, `cuenta_usuario_id` ASC),
  CONSTRAINT `fk_credito_cuenta1`
    FOREIGN KEY (`cuenta_num_cuenta` , `cuenta_usuario_id`)
    REFERENCES `banco`.`cuenta` (`num_cuenta` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`pagos` (
  `cuenta_num_cuenta` INT NOT NULL,
  `cuenta_usuario_id` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `monto` INT NULL,
  `concepto` VARCHAR(255) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`cuenta_num_cuenta`, `cuenta_usuario_id`),
  CONSTRAINT `fk_table1_cuenta1`
    FOREIGN KEY (`cuenta_num_cuenta` , `cuenta_usuario_id`)
    REFERENCES `banco`.`cuenta` (`num_cuenta` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`transferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`transferencias` (
  `ahorro_id_horro` INT NOT NULL,
  `ahorro_cuenta_num_cuenta` INT NOT NULL,
  `ahorro_cuenta_usuario_id` INT NOT NULL,
  `cuenta_num_cuenta` INT NOT NULL,
  `cuenta_usuario_id` INT NOT NULL,
  `monto` INT NOT NULL,
  `fecha_hora_tr` DATETIME NOT NULL,
  `concepto` VARCHAR(255) NOT NULL,
  `estatus` INT NOT NULL,
  PRIMARY KEY (`ahorro_id_horro`, `ahorro_cuenta_num_cuenta`, `ahorro_cuenta_usuario_id`, `cuenta_num_cuenta`, `cuenta_usuario_id`),
  INDEX `fk_transferencias_ahorro1_idx` (`ahorro_id_horro` ASC, `ahorro_cuenta_num_cuenta` ASC, `ahorro_cuenta_usuario_id` ASC),
  CONSTRAINT `fk_transferencias_cuenta1`
    FOREIGN KEY (`cuenta_num_cuenta` , `cuenta_usuario_id`)
    REFERENCES `banco`.`cuenta` (`num_cuenta` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferencias_ahorro1`
    FOREIGN KEY (`ahorro_id_horro` , `ahorro_cuenta_num_cuenta` , `ahorro_cuenta_usuario_id`)
    REFERENCES `banco`.`ahorro` (`id_horro` , `cuenta_num_cuenta` , `cuenta_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
