
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos
 */
public class menu extends javax.swing.JFrame {

    Connection con=null;
    Statement stmt=null;
    String url = "jdbc:mysql://localhost:3306/ticket3";  
    String usuario = "root";
    String contraseña = "5515"; 
    public menu() {
        initComponents();
        ConsultaIdTicket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altaCaja = new javax.swing.JButton();
        altaProducto = new javax.swing.JButton();
        altaSucursal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        ComprarMenu = new javax.swing.JButton();
        ventaDia = new javax.swing.JButton();
        ventaMes = new javax.swing.JButton();
        ventaProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        altaCaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        altaCaja.setText("Alta Caja");
        altaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCajaActionPerformed(evt);
            }
        });

        altaProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        altaProducto.setText("Alta Producto");
        altaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaProductoActionPerformed(evt);
            }
        });

        altaSucursal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        altaSucursal.setText("Alta Sucursal");
        altaSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaSucursalActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Walmart_Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salir.setText("Cerrar Sesion");

        ComprarMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComprarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        ComprarMenu.setText("Comprar");
        ComprarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarMenuActionPerformed(evt);
            }
        });

        ventaDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ventaDia.setText("Ventas del Día");
        ventaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaDiaActionPerformed(evt);
            }
        });

        ventaMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ventaMes.setText("Ventas por\nDepartamento");

        ventaProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ventaProducto.setText("Ventas Por Producto");
        ventaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        jLabel1.setText("Consultas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ventaMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ventaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ventaProducto))
                        .addGap(135, 135, 135)
                        .addComponent(ComprarMenu)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(altaProducto)
                        .addGap(17, 17, 17)
                        .addComponent(altaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(altaSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altaProducto)
                            .addComponent(altaCaja)
                            .addComponent(altaSucursal))
                        .addGap(79, 79, 79)
                        .addComponent(ComprarMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(salir)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ventaDia)
                        .addGap(18, 18, 18)
                        .addComponent(ventaProducto)
                        .addGap(14, 14, 14)
                        .addComponent(ventaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaProductoActionPerformed
        altaProducto abrir = new altaProducto();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaProductoActionPerformed

    private void altaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCajaActionPerformed
        altaCaja abrir = new altaCaja();
        abrir.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_altaCajaActionPerformed

    private void altaSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaSucursalActionPerformed
        altaSucursal abrir = new altaSucursal();
        abrir.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_altaSucursalActionPerformed

    private void ConsultaIdTicket(){
        
    }
    
    private void ComprarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarMenuActionPerformed
       
        nuevaCompra abrir = new nuevaCompra();
        this.setVisible(false);
        abrir.setVisible(true);
  
    }//GEN-LAST:event_ComprarMenuActionPerformed

    private void ventaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaDiaActionPerformed
    ConsultaVentaDia abrir = new ConsultaVentaDia();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_ventaDiaActionPerformed

    private void ventaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaProductoActionPerformed
    ConsultaVentaProducto abrir = new ConsultaVentaProducto();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_ventaProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComprarMenu;
    private javax.swing.JButton altaCaja;
    private javax.swing.JButton altaProducto;
    private javax.swing.JButton altaSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton salir;
    private javax.swing.JButton ventaDia;
    private javax.swing.JButton ventaMes;
    private javax.swing.JButton ventaProducto;
    // End of variables declaration//GEN-END:variables
}
