/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import auxiliar.CrearTabla;
import bd.Consulta;
import controlador.ControlConsultaProductos;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author charlis
 */
public class VistaConsultaProductos extends javax.swing.JFrame {

    private final ControlConsultaProductos controlador;
    private VistaOrdenarPedido vistaPedido;
    private JTable tabla;
    public JScrollPane scrollPane ;
    public Object[][] datos;
    TableColumnModel columnModel;
    DefaultTableModel tableModel;
    
    public VistaConsultaProductos() {
        controlador = new ControlConsultaProductos(this);
        initComponents();
        configurarComponentes();
    }
    
    private void configurarComponentes(){
        
        String[] columnas = {"Nombre","Proveedor", "Precio Compra", "Descripcion"};
        
        Consulta consulta=new Consulta(); 
        datos = consulta.productos();
        
        

       
        tabla = new JTable(new CrearTabla(datos,columnas));
        tabla.setPreferredScrollableViewportSize(new Dimension(500, 200));
        
        columnModel = tabla.getColumnModel();
        DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        
       
        
        //for (int i = 0; i < columnModel.getColumnCount(); i++) {
            //columnModel.getColumn(2).setCellRenderer(alinear);
        //}
        
        
        
        
        scrollPane = new JScrollPane(tabla);
        scrollPane.setBounds(30, 60, 700,200);
        
        tableModel = (DefaultTableModel) tabla.getModel();
        
        
        agregar.addActionListener(controlador);
        
        add(scrollPane);
        
        
        
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos");
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un producto y da click en agregar");

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buyadd48.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregar)
                        .addGap(345, 345, 345))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(agregar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaProductos().setVisible(true);
            }
        });
    }

    public JTable getTabla() {
        return tabla;
    }

    public JButton getAgregar() {
        return agregar;
    }

    public void setVistaPedido(VistaOrdenarPedido vistaPedido) {
        this.vistaPedido = vistaPedido;
    }

    public VistaOrdenarPedido getVistaPedido() {
        return vistaPedido;
    }

    public TableColumnModel getColumnModel() {
        return columnModel;
    }

    public DefaultTableModel getTableModel() {
        return tableModel;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
