-- MySQL Script generated by MySQL Workbench
-- lun 29 may 2017 20:56:38 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idproveedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(80) NULL,
  PRIMARY KEY (`idproveedor`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `direccion_UNIQUE` (`direccion` ASC),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(95) NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idcargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcargo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `idempleado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `idcargo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idempleado`, `idcargo`),
  INDEX `fk_empleado_cargo1_idx` (`idcargo` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_empleado_cargo1`
    FOREIGN KEY (`idcargo`)
    REFERENCES `mydb`.`cargo` (`idcargo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaPedido` DATE NOT NULL,
  `fechaEntrega` DATE NULL,
  `idempleado` INT UNSIGNED NOT NULL,
  `detalles` VARCHAR(85) NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`idpedido`, `idempleado`),
  INDEX `fk_pedido_empleado1_idx` (`idempleado` ASC),
  CONSTRAINT `fk_pedido_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor_producto` (
  `idproveedor` INT UNSIGNED NOT NULL,
  `idproducto` INT UNSIGNED NOT NULL,
  INDEX `fk_proveedor_has_producto_producto1_idx` (`idproducto` ASC),
  INDEX `fk_proveedor_has_producto_proveedor1_idx` (`idproveedor` ASC),
  PRIMARY KEY (`idproveedor`, `idproducto`),
  CONSTRAINT `fk_proveedor_has_producto_proveedor1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `mydb`.`proveedor` (`idproveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_proveedor_has_producto_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `mydb`.`producto` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordenCompra` (
  `idorden` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idproducto` INT UNSIGNED NOT NULL,
  `idproveedor` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `idpedido` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idorden`, `idproducto`, `idproveedor`, `idpedido`),
  INDEX `fk_ordenCompra_pedido1_idx` (`idpedido` ASC),
  INDEX `fk_ordenCompra_proveedor_producto1_idx` (`idproveedor` ASC, `idproducto` ASC),
  CONSTRAINT `fk_ordenCompra_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordenCompra_proveedor_producto1`
    FOREIGN KEY (`idproveedor` , `idproducto`)
    REFERENCES `mydb`.`proveedor_producto` (`idproveedor` , `idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
