
SELECT WORKDEPT,SUM(SALARY) AS SUM_SALARY FROM EMPLOYEE GROUP BY WORKDEPT;

SELECT WORKDEPT, COUNT(*) AS EMP_COUNT FROM EMPLOYEE GROUP BY WORKDEPT;

SELECT WORKDEPT, COUNT(*) AS EMP_COUNT FROM EMPLOYEE GROUP BY WORKDEPT HAVING COUNT(*) > 3 ORDER BY count(*) asc;

SELECT WORKDEPT, COUNT(*) AS DESIGNER FROM EMPLOYEE  WHERE JOB LIKE'DESIGNER';   

SELECT WORKDEPT,SEX,ROUND(AVG(SALARY),2)AS AVG_SALARY,ROUND(AVG(BONUS),2) AS AVG_BONUS,ROUND(AVG(COMM),2) AS AVG_COMM,COUNT(*) AS COUNT_ 
FROM EMPLOYEE GROUP BY WORKDEPT COUNT(*) >= 2;