ALTER TABLE proveedor ADD column Credito double not null;
UPDATE proveedor set Credito=20000;
UPDATE socioClub SET idClub = (SELECT idClub FROM club WHERE nombre='El Molinito') WHERE idClub=(SELECT idClub FROM club WHERE nombre='TEPEYAC');
UPDATE proveedor set Credito = (Credito-Credito*0.4) WHERE nombre = 'SABRITAS';
UPDATE Producto SET idProveedor=30 WHERE idProveedor=25 OR idProveedor =24 OR idProveedor=27;
UPDATE proveedor set Credito = 10000 WHERE nombre like 'S%';
UPDATE producto set precioUnitario=200 WHERE idProducto=15;
UPDATE producto SET precioUnitario = precioUnitario*1.10;
UPDATE club SET nombre = UPPER(nombre);
UPDATE sociosc SET direccion='Direccion de Juan' WHERE nombre LIKE '% % %JUAN %';
ALTER TABLE producto CHANGE precioUnitario precioUnitario DECIMAL(7,2);
SELECT * FROM gerente WHERE idGerente not in(50,60,70,80,90,100,110,120,150,130,200,230,300);
SELECT * FROM club WHERE nombre LIKE '_e%';
SELECT * FROM sociosc WHERE nombre LIKE 'A%';
SELECT s.nombre FROM servicio s,club c, servicioClub sc WHERE c.idClub=sc.idClub AND s.idServicio=sc.idServicio AND c.nombre LIKE 'Quer%taro';
SELECT * FROM proveedor WHERE nombre LIKE '_a%' or nombre LIKE '_e%' or nombre LIKE '_i%' or nombre LIKE '_o%' or nombre LIKE '_u%';
SELECT ROUND(AVG(precioUnitario),2) as PROM FROM Producto;
SELECT p.nombre, c.nombre FROM proveedor p, club c,proveedorSams ps WHERE c.idClub=ps.idClub AND p.idProveedor = ps.idProveedor AND c.nombre = 'TEPEYAC' ORDER BY 1;
SELECT s.nombre as SOCIO, c.nombre as NOMBRE_TIENDA FROM socio s, socioclub sc, club c WHERE sc.idSocio=s.idSocio AND sc.idClub = c.idClub ORDER BY s.nombre;
SELECT gerente.nombre  FROM gerente,club, WHERE gerente.idClub = club.idClub AND club.nombre = 'Hiperplaza Texcoco';